OCPBUGS-3114: HyperShift: Do not accept empty infrastructure name
openshift/cluster-network-operator pull request #1611
Opened 2022-11-03 16:35 UTC by kyrtapz

During CNO startup there is a small chance that it will read the infrastructure object before its `Status.InfrastructureName` properly updated by hosted cluster config operator. 

To address such scenario do not accept empty InfrastructureName. 
Additionally add a retry to avoid unnecessary restarts.

Signed-off-by: Patryk Diak <pdiak@redhat.com>

2022-11-03 16:39 UTC, kyrtapz commented
/assign @jcaamano

2022-11-04 08:59 UTC, kyrtapz commented
/retest

2022-11-04 13:27 UTC, kyrtapz commented
/test ci/prow/e2e-hypershift-ovn

2022-11-04 13:31 UTC, kyrtapz commented
/test e2e-hypershift-ovn

2022-11-08 09:12 UTC, kyrtapz commented
/retest

2022-11-08 17:27 UTC, jcaamano requested changes

2022-11-08 17:27 UTC, jcaamano commented on pkg/operator/operator.go
>  	configv1 "github.com/openshift/api/config/v1"
could you fix this import as well?

2022-11-10 12:05 UTC, jcaamano commented
/lgtm
/approve

2022-11-10 14:16 UTC, kyrtapz commented
/retest-required

2022-11-10 14:24 UTC, kyrtapz commented
/cherry-pick release-4.12

2022-11-21 09:34 UTC, kyrtapz commented
/retest-required

2022-11-21 12:08 UTC, kyrtapz commented
/retest-required

2022-11-22 01:17 UTC, merged

2022-11-22 08:44 UTC, kyrtapz commented
/cherry-pick release-4.11

2022-12-07 09:15 UTC, kyrtapz commented on pkg/operator/operator.go
> +	klog.Info("Creating status manager for %s cluster", cluster)
https://github.com/openshift/cluster-network-operator/pull/1650