OCPBUGSM-44162: Remove references to the hosts kubeconfig
openshift/cluster-network-operator pull request #1612
Opened 2022-11-03 16:54 UTC by kyrtapz

Since https://github.com/openshift/cluster-network-operator/pull/976 we are no longer using the hosts kubeconfig.

Remove the references to the old approach.

Signed-off-by: Patryk Diak <pdiak@redhat.com>

2022-11-03 16:59 UTC, kyrtapz commented
/bugzilla refresh

2022-11-03 17:00 UTC, kyrtapz commented
/bugzilla refresh

2022-11-03 17:16 UTC, kyrtapz commented
/bugzilla refresh

2022-11-04 08:58 UTC, kyrtapz commented
/retest

2022-11-08 08:49 UTC, kyrtapz commented
/retest

2022-11-08 17:21 UTC, jcaamano requested changes

2022-11-08 17:21 UTC, jcaamano commented on cmd/cluster-network-operator/main.go
> +	"github.com/openshift/cluster-network-operator/pkg/version"
oops bad import group

2022-11-09 11:55 UTC, kyrtapz commented on cmd/cluster-network-operator/main.go
> +	"github.com/openshift/cluster-network-operator/pkg/version"
fixed

2022-11-10 12:02 UTC, jcaamano commented
@kyrtapz wanted to check with you a couple of things:

1. no potential downgrade issue here, since probably the environment file has been available since a few versions already.
2. could you check with @zshi-redhat if microshift depends on any of this?

2022-11-10 13:54 UTC, kyrtapz commented
>     1. no potential downgrade issue here, since probably the environment file has been available since a few versions already.
There should be no downgrade issues, `/etc/kubernetes/apiserver-url.env` is available since 4.7 and we stopped reading the kubeconfig here: https://github.com/openshift/cluster-network-operator/pull/976
https://bugzilla.redhat.com/show_bug.cgi?id=2083334#c1
> 
>     2. could you check with @zshi-redhat if microshift depends on any of this?
From what I understand CNO is not run in microshift so this should not affect it at all(Thanks @pmtk!)
@zshi-redhat please help us confirm that there is no indirect impact on microshift.

2022-11-10 14:43 UTC, jcaamano commented
After talking with @zshi-redhat, this is a non issue for microshift.

2022-11-10 15:02 UTC, jcaamano commented
/lgtm
/approve

2022-11-21 09:03 UTC, kyrtapz commented
/retest-required

2022-11-21 14:09 UTC, merged