OCPBUGS-3272: Unhealthy Readiness Probe failing ci
openshift/cluster-network-operator pull request #1665
Opened 2022-12-13 15:22 UTC by bpickard22

When a cluster is created, it typically takes ~2 minutes for  the databases to start up and form the Raft cluster. Before this occurs, there will be no DB endpointsm so the node containers that are waiting for them and failing readiness tests will cause alerts, which cause ci failures / flakes

We can avoid this problem by waiting 2 minutes to start the liveness probe, and reducing its polling rate

Signed-off-by: Ben Pickard <bpickard@redhat.com>

2022-12-13 15:23 UTC, bpickard22 commented
@dcbw PTAL

2022-12-13 15:24 UTC, bpickard22 commented
/jira refresh

2022-12-13 16:20 UTC, jluhrsen commented
IIRC, CI will fail if we get 20+ of these alerts. So, I think as long as you make sure the polling delay and intervals would ensure we don't get 20+ alerts while a cluster is coming up you should be able to avoid the CI failures.

2022-12-13 16:21 UTC, bpickard22 commented
Another possible solution here would be leaving the initial delay at 5 seconds but reducing the polling rate to around 30 seconds to help with the case when the container restarts but the dbs are still healthy

2022-12-13 19:49 UTC, flavio-fernandes reviewed
/lgtm

2022-12-13 21:29 UTC, bpickard22 commented
/retest

2022-12-14 14:58 UTC, bpickard22 commented
/retest-required

2022-12-20 16:07 UTC, bpickard22 commented
/assign @jcaamano

2023-01-12 20:28 UTC, trozet requested changes
don't you also need this change in the managed path as well?

2023-01-16 10:31 UTC, jcaamano commented
@bpickard22 we had discussed at one point in out meeting to increase `periodSeconds` but leave `initialDelaySeconds` as is; as to not unnecessarily delay start (even though it might take 2 minutes for things to be ready, maybe one day in the future it takes less time). We are probably talking about 1 probe failure difference, between 4 or 5 during those 2 minutes.
Do you know what is the alert threshold? How many probes have to fail to get the alert?
Also you mention in the PR message `waiting 2 minutes to start the liveness probe` but is really 30 seconds, right? Just crosschecking.

2023-01-20 18:48 UTC, bpickard22 commented
@jcaamano i forgot to correct the commit, message, I will take care of that, and I have changed the intialDelaySeconds back to 5 seconds.  The alert threshold is 20 failures (from here) https://github.com/openshift/origin/blob/2154d73eed665b1a0951f59ee638e52242d64a6c/pkg/synthetictests/duplicated_events.go#L25) so as long as we stay under that we are good.

2023-01-20 18:52 UTC, bpickard22 commented
@trozet made the change in the managed path

2023-01-20 19:12 UTC, flavio-fernandes commented
/lgtm

2023-01-25 18:13 UTC, bpickard22 commented
/retest-required

2023-01-25 22:09 UTC, flavio-fernandes commented
/retest-required

2023-01-26 13:54 UTC, flavio-fernandes commented
/test e2e-network-migration

2023-01-26 13:56 UTC, flavio-fernandes commented
@bpickard22 the job e2e-network-migration has not passed since Jan/12/23.
Maybe time ask for an override and approve?

2023-01-26 18:41 UTC, dcbw commented
/override ci/prow/e2e-network-migration
unrelated to this change

2023-01-26 18:42 UTC, dcbw commented
/approve

2023-01-26 19:32 UTC, merged