Add OpenStack platform to list of allowed dual-stack clusters
openshift/cluster-network-operator pull request #1697
Opened 2023-02-01 15:02 UTC by MaysaMacedo

2023-02-17 17:34 UTC, MaysaMacedo commented
/hold
Dual-stack support needs to merge on installer first

2023-02-21 12:56 UTC, MaysaMacedo commented
/test e2e-aws-sdn-multi

2023-05-18 12:59 UTC, dulek requested changes

2023-06-27 21:55 UTC, MaysaMacedo commented
/retest-required

2023-06-27 21:56 UTC, MaysaMacedo commented on pkg/network/render.go
> +	string(configv1.OpenStackPlatformType),
done. Thanks!

@dulek Can you take another look?

2023-06-28 13:47 UTC, dulek reviewed
/lgtm

2023-06-28 13:47 UTC, dulek commented on pkg/network/render.go
> +		} else if string(configv1.OpenStackPlatformType) == string(infraRes.PlatformType) {
We could probably just split `isSupportedDualStackPlatform()` into another function to be used here, but no big deal if it's just OpenStack that doesn't support migrations.

2023-06-29 15:03 UTC, MaysaMacedo commented
/cc @jcaamano 

can you have a look on this PR?

2023-06-29 15:10 UTC, MaysaMacedo commented
I plan to remove the hold as soon as https://github.com/openshift/installer/pull/6797 gets merged

2023-07-10 17:51 UTC, MaysaMacedo commented
/retest-required

2023-07-10 20:01 UTC, dcbw commented
We'd probably need a Docs PR then to note that OSP isn't supported for conversion, unless that's getting added very soon?

2023-07-10 20:02 UTC, dcbw commented
Also (hopefully??) we can do a dualstack OSP CI job?

2023-07-16 13:18 UTC, MaysaMacedo commented
/hold cancel
/retest-required

2023-07-16 16:08 UTC, MaysaMacedo commented
@dcbw we're targeting 4.15 to GA dual-stack, which will include the support for conversion from IPv4 single stack to dual-stack clusters. On 4.14 dual-stack support will be tech preview.

I'm adding [a note in the installer](https://github.com/openshift/installer/pull/7269/files#diff-aa965cd93a12a9ef8cd6b3b94c905e5be363422f096177b20b251a0433fd3222R16) docs about the no support for conversion and will also add to the openshift-docs.

We're working on the CI at the moment https://issues.redhat.com/browse/OSASINFRA-2251.

2023-07-27 19:04 UTC, MaysaMacedo commented
/retest-required

2023-07-27 22:43 UTC, MaysaMacedo commented
/retest-required

2023-07-28 07:43 UTC, dulek commented
/retest-required

2023-07-28 10:47 UTC, MaysaMacedo commented
/retest-required

2023-07-28 23:45 UTC, MaysaMacedo commented
/retest-required

2023-07-30 15:19 UTC, MaysaMacedo commented
/retest

2023-07-30 23:33 UTC, MaysaMacedo commented
/retest-required

2023-07-31 11:23 UTC, MaysaMacedo commented
/retest-required

2023-08-01 11:50 UTC, MaysaMacedo commented
/retest-required

2023-08-01 20:16 UTC, MaysaMacedo commented
/retest-required

2023-08-01 22:04 UTC, merged