OCPBUGS-16019: prevent creation of multiple cni-sysctl-allowlist-ds pods
openshift/cluster-network-operator pull request #1904
Opened 2023-07-17 15:06 UTC by mlguerrero12

The daemonset has a BestEffort QoS which  means that in some cases, the pods won't ever be scheduled.
This also prevents unwanted retries when one or more pods are not ready due to issues with the cluster.
https://issues.redhat.com/browse/OCPBUGS-15818 (BestEffort Daemonset cni-sysctl-allowlist-ds)

When there are issues with the cluster such as in https://issues.redhat.com/browse/OCPBUGS-15284, some pods are stuck in the terminating state which affects subsequent reconciliations of the allowlist controller.

2023-07-17 15:07 UTC, mlguerrero12 commented
/jira refresh

2023-07-18 07:27 UTC, mlguerrero12 commented
/retest-required

2023-07-18 09:37 UTC, mlguerrero12 commented
/retest

2023-07-19 07:44 UTC, mlguerrero12 commented
/retest

2023-07-20 07:49 UTC, mlguerrero12 commented
/retest-required

2023-07-20 13:56 UTC, mlguerrero12 commented
/retest

2023-07-20 17:30 UTC, dougbtv requested changes

2023-07-20 17:30 UTC, dougbtv commented on pkg/controller/allowlist/allowlist_controller.go
> +func getDeamonSet(ctx context.Context, client cnoclient.Client) (*appsv1.DaemonSet, error) {
nit:  `getDaemonSet`

2023-07-20 17:55 UTC, dougbtv commented
/approve

2023-07-21 11:19 UTC, mlguerrero12 commented on pkg/controller/allowlist/allowlist_controller.go
> +func getDeamonSet(ctx context.Context, client cnoclient.Client) (*appsv1.DaemonSet, error) {
Fixed. Thanks.

2023-07-21 14:43 UTC, cgoncalves commented
/lgtm

2023-07-25 09:21 UTC, mlguerrero12 commented
/retest-required

2023-07-25 12:27 UTC, mlguerrero12 commented
/retest-required

2023-07-26 06:59 UTC, mlguerrero12 commented
/retest-required

2023-07-26 17:29 UTC, aravindhp commented
/retest-required

2023-07-26 18:16 UTC, aravindhp commented
/retest-required

cluster [failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1904/pull-ci-openshift-cluster-network-operator-master-e2e-vsphere-ovn-windows/1684254669041307648) to come up in e2e-vsphere-ovn-windows:
```
level=error msg=Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane.
```

2023-07-27 15:19 UTC, aravindhp commented
/retest-required

Latest run [failed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1904/pull-ci-openshift-cluster-network-operator-master-e2e-vsphere-ovn-windows/1684297978593939456/artifacts/e2e-vsphere-ovn-windows/gather-extra/artifacts/pods/openshift-machine-api_machine-api-controllers-d6d69d645-mk7hh_machine-controller.log) on Windows node deletion:
```
0726 22:45:12.316499       1 actuator.go:60] e2e-wm-v8w2r error: e2e-wm-v8w2r: reconciler failed to Delete machine: unable to remove finalizer for IP address claims: unable to list IPAddressClaims: failed to get API group resources: unable to retrieve the complete list of server APIs: ipam.cluster.x-k8s.io/v1alpha1: the server could not find the requested resource
E0726 22:45:12.316532       1 controller.go:224] e2e-wm-v8w2r: failed to delete machine: e2e-wm-v8w2r: reconciler failed to Delete machine: unable to remove finalizer for IP address claims: unable to list IPAddressClaims: failed to get API group resources: unable to retrieve the complete list of server APIs: ipam.cluster.x-k8s.io/v1alpha1: the server could not find the requested resource
E0726 22:45:12.316572       1 controller.go:324]  "msg"="Reconciler error" "error"="e2e-wm-v8w2r: reconciler failed to Delete machine: unable to remove finalizer for IP address claims: unable to list IPAddressClaims: failed to get API group resources: unable to retrieve the complete list of server APIs: ipam.cluster.x-k8s.io/v1alpha1: the server could not find the requested resource" "controller"="machine-controller" "name"="e2e-wm-v8w2r" "namespace"="openshift-machine-api" "object"={"name":"e2e-wm-v8w2r","namespace":"openshift-machine-api"} "reconcileID"="c874a4ad-7c8d-40d3-9c0c-6a623a67a88e"
I0726 22:45:12.316623       1 recorder.go:104] events "msg"="e2e-wm-v8w2r: reconciler failed to Delete machine: unable to remove finalizer for IP address claims: unable to list IPAddressClaims: failed to get API group resources: unable to retrieve the complete list of server APIs: ipam.cluster.x-k8s.io/v1alpha1: the server could not find the requested resource" "object"={"kind":"Machine","namespace":"openshift-machine-api","name":"e2e-wm-v8w2r","uid":"ee16f244-fe84-44f8-be53-2972fc456d4b","apiVersion":"machine.openshift.io/v1beta1","resourceVersion":"49193"} "reason"="FailedDelete" "type"="Warning"
I0726 22:45:35.923415       1 controller.go:57] controllers/MachineSet "msg"="Reconciling" "machineset"="ci-op-dlr2bxdn-36a6b-mqcv9-worker-0" "namespace"="openshift-machine-api"
```

2023-07-27 18:10 UTC, aravindhp commented
The windows e2e test is failing because of [OCPBUGS-16925](https://issues.redhat.com//browse/OCPBUGS-16925). Feel free to override the test as I have confirmed that the test is passing otherwise. Please don't take this as a reason to permanently disable the test.

2023-07-28 15:03 UTC, dcbw commented
/override ci/prow/e2e-vsphere-ovn-windows

2023-07-30 21:58 UTC, mlguerrero12 commented
/retest-required

2023-07-31 07:27 UTC, mlguerrero12 commented
/retest-required

2023-07-31 14:03 UTC, mlguerrero12 commented
/retest-required

2023-08-01 09:21 UTC, mlguerrero12 commented
/retest-required

2023-08-01 11:58 UTC, mlguerrero12 commented
/retest-required

2023-08-01 19:56 UTC, aravindhp commented
/retest-required

The Windows test is failing because the operator is unable to approve the CSR:
```
2023-08-01T18:07:57Z	ERROR	Reconciler error	{"controller": "certificatesigningrequest", "controllerGroup": "certificates.k8s.io", "controllerKind": "CertificateSigningRequest", "CertificateSigningRequest": {"name":"csr-hkpzl"}, "namespace": "", "name": "csr-hkpzl", "reconcileID": "eb7a78fc-ceb4-46cb-8473-44fb37c21b86", "error": "WMCO CSR Approver could not approve CSR csr-hkpzl: could not validate contents for approval of CSR: csr-hkpzl: error validating node name winhost-91bny for CSR: csr-hkpzl: unable to map node name to the addresses of Windows instances: failed to lookup DNS for IP 192.168.107.54: lookup 54.107.168.192.in-addr.arpa. on 172.30.0.10:53: no such host"}
```

This implies the reverse PTR records have not been created in the CI environment. If this is happening consistently please escalate on #vsphere-ci-triage.

2023-08-03 08:04 UTC, mlguerrero12 commented
/hold cancel
/retest-required

2023-08-04 09:03 UTC, mlguerrero12 commented
/retest-required

2023-08-07 07:58 UTC, mlguerrero12 commented
/hold cancel

2023-08-07 08:01 UTC, cgoncalves commented
/lgtm

2023-08-07 11:54 UTC, mlguerrero12 commented
/retest-required

2023-08-08 06:42 UTC, mlguerrero12 commented
/retest-required

2023-08-08 09:31 UTC, merged

2023-08-08 09:57 UTC, mlguerrero12 commented
/cherry-pick release-4.13