OCPBUGS-24690: Disable network-node-identity on ROKS
openshift/cluster-network-operator pull request #2197
Opened 2024-01-12 10:48 UTC by kyrtapz

In environments with external control plane topology, the API server is deployed out of cluster. 
This means that CNO cannot easily predict how to deploy and enforce the node identity webhook. 
IBMCloud uses an external control plane topology with Calico as the CNI for both HyperShift based ROKS deployments and IBM ROKS Toolkit based ROKS deployments.
/cc @dougbtv @s1061123

2024-01-12 10:48 UTC, kyrtapz commented
/jira refresh

2024-01-18 10:23 UTC, kyrtapz commented
/retest

2024-01-18 13:08 UTC, s1061123 commented
/lgtm

2024-01-18 17:52 UTC, s1061123 approved these changes

2024-01-19 15:33 UTC, dougbtv commented
/approve

2024-01-19 21:01 UTC, rtheis requested changes
/hold we need to talk about ROKS since the component is deploy and I'm not sure why we wouldn't want it to be deployed.

2024-02-05 13:16 UTC, kyrtapz commented
/retest

2024-02-05 13:17 UTC, kyrtapz commented
/test images

2024-02-06 07:51 UTC, tssurya commented
/retest-required

2024-02-14 16:22 UTC, Joseph-Goergen commented
/retest

2024-02-14 16:47 UTC, rtheis approved these changes
/remove-hold
/lgtm

Thanks for being patient and working with us on these changes.

2024-02-15 13:29 UTC, s1061123 commented
/lgtm

2024-02-15 15:08 UTC, kyrtapz commented
/cherry-pick release-4.15

2024-02-16 15:07 UTC, kyrtapz commented
/retest-required

2024-02-19 08:30 UTC, kyrtapz commented
/label acknowledge-critical-fixes-only

2024-02-19 08:34 UTC, merged