OCPBUGS-31878: Propogate hypershift control plane priority class override to multus
openshift/cluster-network-operator pull request #2335
Opened 2024-04-12 20:10 UTC by lucaspalm

**What this PR does / why we need it**:
The multus-admission-controller component currently does not honor the hypershift custom priority class overrides specified on the hostedcluster.  The custom priority class override feature was first introduced to all other hypershift hosted control plane components in https://github.com/openshift/hypershift/pull/2661.  Multus was left out at the time due to it not being directly managed by the CPO.  These changes extend the hypershift custom priority class override feature to the multus-admission-controller to ensure that this component honors the custom class if it is set.

**Which issue(s) this PR fixes**:
https://issues.redhat.com/browse/OCPBUGS-31878

2024-04-15 14:02 UTC, ricky-rav commented
/assign @dougbtv

2024-04-16 20:21 UTC, lucaspalm commented
/jira refresh

2024-04-17 13:50 UTC, lucaspalm commented
/retest

2024-04-17 18:28 UTC, lucaspalm commented
/retest

2024-04-18 14:37 UTC, lucaspalm commented
/retest-required

2024-04-18 17:35 UTC, lucaspalm commented
/retest-required

2024-05-13 15:12 UTC, lucaspalm commented
/retest

2024-05-20 14:44 UTC, riendeau commented
/retest

2024-05-20 18:06 UTC, riendeau commented
/retest-required

2024-05-21 14:36 UTC, riendeau commented
/retest-required

2024-05-21 15:57 UTC, riendeau commented
/test e2e-hypershift-ovn

2024-05-22 00:04 UTC, riendeau commented
/retest

2024-05-22 16:03 UTC, riendeau commented
/retest

2024-05-23 11:02 UTC, riendeau commented
/retest

2024-05-23 20:10 UTC, riendeau commented
/retest

2024-05-28 15:11 UTC, rtheis commented
/retest-required

2024-05-29 15:50 UTC, riendeau commented
> tide Pending — Not mergeable. Needs lgtm label.

I _think_ all required tests are now passing (`e2e-hypershift-ovn` [doesn't really exist](https://github.com/openshift/cluster-network-operator/pull/2335#issuecomment-2122950766) any more?) , and we just need an `lgtm`?

2024-05-31 16:16 UTC, riendeau requested changes
Please hold for now, pending investigation of default value specification in the template.

2024-05-31 16:18 UTC, rtheis commented
/hold

2024-06-13 11:58 UTC, riendeau approved these changes

2024-06-13 12:01 UTC, riendeau commented
I've gone through and now understand the usage of the `default` func provided by sprig here.

/remove-hold

2024-06-13 15:18 UTC, rtheis approved these changes
/lgtm

2024-06-14 10:13 UTC, rtheis commented
/jira refresh

2024-06-14 10:15 UTC, rtheis commented
@riendeau please fix the Jira problems.

2024-06-14 19:51 UTC, riendeau commented
/jira refresh

2024-06-19 12:02 UTC, enxebre commented on pkg/hypershift/hypershift.go
> +	controlPlanePriorityClassAnnotation, _, err := unstructured.NestedString(hcp.UnstructuredContent(), "metadata", "annotations", "hypershift.openshift.io/control-plane-priority-class")
nit: it'd be nice to have a comment linking the counterpart source code. So when someone with less context reads the context can understand where this is coming from.

2024-06-19 12:02 UTC, enxebre commented
/lgtm

2024-06-19 16:00 UTC, merged

2024-06-19 16:07 UTC, riendeau commented
/cherry-pick release-4.16

2024-06-19 16:09 UTC, rtheis commented
/cherry-pick release-4.16

2024-06-19 16:10 UTC, rtheis commented
/cherry-pick release-4.15